# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ralph < Formula
  desc "Ralph - AI agent loop runner"
  homepage "https://github.com/agentic-metallurgy/ralph"
  version "2026.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v2026.3.3/ralph_2026.3.3_darwin_amd64.tar.gz"
      sha256 "34ca1a783c1abf5f99e2c6449171352090fd5e105ca80655522d4b0feeb664e4"

      define_method(:install) do
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v2026.3.3/ralph_2026.3.3_darwin_arm64.tar.gz"
      sha256 "ca45a54bb6cc517f6fa22c56275bd797ac82b570d9b0fe5e10e7507461963a47"

      define_method(:install) do
        bin.install "ralph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v2026.3.3/ralph_2026.3.3_linux_amd64.tar.gz"
      sha256 "72e648687bb62a1bdd1a9e9372961fb36c91d7fb1755a3ef5b604248b432e720"
      define_method(:install) do
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v2026.3.3/ralph_2026.3.3_linux_arm64.tar.gz"
      sha256 "4503f83117ec6a1efbeb3778bc3fe5ae5afc94681309cadb9c9daed1f6e57659"
      define_method(:install) do
        bin.install "ralph"
      end
    end
  end

  test do
    system "#{bin}/ralph", "--help"
  end
end
