# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ralph < Formula
  desc "Ralph - AI agent loop runner"
  homepage "https://github.com/agentic-metallurgy/ralph"
  version "2026.2.24"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v2026.2.24/ralph_2026.2.24_darwin_amd64.tar.gz"
      sha256 "dfea4ed2980f1e7d09bb889af604614dce20a06b44205530635395b1e40325a7"

      define_method(:install) do
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v2026.2.24/ralph_2026.2.24_darwin_arm64.tar.gz"
      sha256 "a29b2de784100983b99fa84d66cdff54ba59f09f1b6e2e670b6730efafe82ca2"

      define_method(:install) do
        bin.install "ralph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v2026.2.24/ralph_2026.2.24_linux_amd64.tar.gz"
      sha256 "0da18879e686410ff9b653c8866229dd9382b9ff3f275f9f2dcdc108ecc07309"
      define_method(:install) do
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v2026.2.24/ralph_2026.2.24_linux_arm64.tar.gz"
      sha256 "781fe430b22a3d91c83064b488a48cdf6ffb7ccbf3576b5cee4207c6c481d4c5"
      define_method(:install) do
        bin.install "ralph"
      end
    end
  end

  test do
    system "#{bin}/ralph", "--help"
  end
end
