# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ralph < Formula
  desc "Ralph - AI agent loop runner"
  homepage "https://github.com/agentic-metallurgy/ralph"
  version "2026.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v2026.3.2/ralph_2026.3.2_darwin_amd64.tar.gz"
      sha256 "ca5b96b79b71d418a0ae37b17ad02359b0ab7594e8dc569d650ee09bd824bd8c"

      define_method(:install) do
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v2026.3.2/ralph_2026.3.2_darwin_arm64.tar.gz"
      sha256 "4a588523ac63841188fecb0767f1db72f794c039b954a0ba48364ce15306116a"

      define_method(:install) do
        bin.install "ralph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v2026.3.2/ralph_2026.3.2_linux_amd64.tar.gz"
      sha256 "8a9de640524c17003770b3398ecd3d82a1e5a5c638aa5767961bee751624acdc"
      define_method(:install) do
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentic-metallurgy/ralph/releases/download/v2026.3.2/ralph_2026.3.2_linux_arm64.tar.gz"
      sha256 "a332427cb744fe2f7a1a5ede85b7f223c9eca45e2c9a6a40e8465d6d8f4d0441"
      define_method(:install) do
        bin.install "ralph"
      end
    end
  end

  test do
    system "#{bin}/ralph", "--help"
  end
end
